//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billing_system
{
    partial class UserManagementControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            headerPanel = new Panel();
            lblTitle = new Label();
            btnAddUser = new Button();
            searchPanel = new Panel();
            txtSearchUsers = new TextBox();
            dgvUsers = new DataGridView();
            colUserId = new DataGridViewTextBoxColumn();
            colUsername = new DataGridViewTextBoxColumn();
            colRole = new DataGridViewTextBoxColumn();
            colCreated = new DataGridViewTextBoxColumn();
            colAction = new DataGridViewButtonColumn();
            headerPanel.SuspendLayout();
            searchPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvUsers).BeginInit();
            SuspendLayout();
            // 
            // headerPanel
            // 
            headerPanel.Controls.Add(lblTitle);
            headerPanel.Controls.Add(btnAddUser);
            headerPanel.Dock = DockStyle.Top;
            headerPanel.Location = new Point(20, 20);
            headerPanel.Name = "headerPanel";
            headerPanel.Padding = new Padding(0, 0, 0, 10);
            headerPanel.Size = new Size(760, 50);
            headerPanel.TabIndex = 0;
            // 
            // lblTitle
            // 
            lblTitle.Dock = DockStyle.Left;
            lblTitle.Font = new Font("Segoe UI", 18F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblTitle.Location = new Point(0, 0);
            lblTitle.Name = "lblTitle";
            lblTitle.Size = new Size(250, 40);
            lblTitle.TabIndex = 1;
            lblTitle.Text = "User Management";
            lblTitle.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // btnAddUser
            // 
            btnAddUser.BackColor = Color.FromArgb(41, 213, 146);
            btnAddUser.Cursor = Cursors.Hand;
            btnAddUser.Dock = DockStyle.Right;
            btnAddUser.FlatAppearance.BorderSize = 0;
            btnAddUser.FlatStyle = FlatStyle.Flat;
            btnAddUser.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnAddUser.ForeColor = Color.White;
            btnAddUser.Location = new Point(600, 0);
            btnAddUser.Name = "btnAddUser";
            btnAddUser.Size = new Size(160, 40);
            btnAddUser.TabIndex = 0;
            btnAddUser.Text = "+ Add New User";
            btnAddUser.UseVisualStyleBackColor = false;
            btnAddUser.Click += btnAddUser_Click;
            // 
            // searchPanel
            // 
            searchPanel.Controls.Add(txtSearchUsers);
            searchPanel.Dock = DockStyle.Top;
            searchPanel.Location = new Point(20, 70);
            searchPanel.Name = "searchPanel";
            searchPanel.Padding = new Padding(0, 10, 0, 10);
            searchPanel.Size = new Size(760, 55);
            searchPanel.TabIndex = 1;
            // 
            // txtSearchUsers
            // 
            txtSearchUsers.Dock = DockStyle.Fill;
            txtSearchUsers.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtSearchUsers.ForeColor = Color.Gray;
            txtSearchUsers.Location = new Point(0, 10);
            txtSearchUsers.MinimumSize = new Size(0, 35);
            txtSearchUsers.Name = "txtSearchUsers";
            txtSearchUsers.Size = new Size(760, 45);
            txtSearchUsers.TabIndex = 0;
            txtSearchUsers.Text = "Search by username...";
            // 
            // dgvUsers
            // 
            dgvUsers.AllowUserToAddRows = false;
            dgvUsers.AllowUserToDeleteRows = false;
            dgvUsers.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = Color.WhiteSmoke;
            dgvUsers.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dgvUsers.BackgroundColor = Color.FromArgb(245, 246, 250);
            dgvUsers.BorderStyle = BorderStyle.None;
            dgvUsers.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgvUsers.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.FromArgb(245, 246, 250);
            dataGridViewCellStyle2.Font = new Font("Segoe UI", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            dataGridViewCellStyle2.ForeColor = Color.Black;
            dataGridViewCellStyle2.SelectionBackColor = SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            dgvUsers.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgvUsers.ColumnHeadersHeight = 40;
            dgvUsers.Columns.AddRange(new DataGridViewColumn[] { colUserId, colUsername, colRole, colCreated, colAction });
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = SystemColors.Window;
            dataGridViewCellStyle3.Font = new Font("Segoe UI", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            dataGridViewCellStyle3.ForeColor = SystemColors.ControlText;
            dataGridViewCellStyle3.Padding = new Padding(5, 0, 0, 0);
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(220, 235, 252);
            dataGridViewCellStyle3.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgvUsers.DefaultCellStyle = dataGridViewCellStyle3;
            dgvUsers.Dock = DockStyle.Fill;
            dgvUsers.EnableHeadersVisualStyles = false;
            dgvUsers.GridColor = Color.Gainsboro;
            dgvUsers.Location = new Point(20, 125);
            dgvUsers.Name = "dgvUsers";
            dgvUsers.ReadOnly = true;
            dgvUsers.RowHeadersVisible = false;
            dgvUsers.RowHeadersWidth = 72;
            dgvUsers.RowTemplate.Height = 40;
            dgvUsers.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvUsers.Size = new Size(760, 455);
            dgvUsers.TabIndex = 2;
            // 
            // colUserId
            // 
            colUserId.HeaderText = "USER ID";
            colUserId.MinimumWidth = 9;
            colUserId.Name = "colUserId";
            colUserId.ReadOnly = true;
            colUserId.Width = 175;
            // 
            // colUsername
            // 
            colUsername.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            colUsername.HeaderText = "USERNAME";
            colUsername.MinimumWidth = 9;
            colUsername.Name = "colUsername";
            colUsername.ReadOnly = true;
            // 
            // colRole
            // 
            colRole.HeaderText = "ROLE";
            colRole.MinimumWidth = 9;
            colRole.Name = "colRole";
            colRole.ReadOnly = true;
            colRole.Width = 150;
            // 
            // colCreated
            // 
            colCreated.HeaderText = "DATE CREATED";
            colCreated.MinimumWidth = 9;
            colCreated.Name = "colCreated";
            colCreated.ReadOnly = true;
            colCreated.Width = 150;
            // 
            // colAction
            // 
            colAction.FlatStyle = FlatStyle.Flat;
            colAction.HeaderText = "ACTIONS";
            colAction.MinimumWidth = 9;
            colAction.Name = "colAction";
            colAction.ReadOnly = true;
            colAction.Text = "Edit";
            colAction.UseColumnTextForButtonValue = true;
            colAction.Width = 120;
            // 
            // UserManagementControl
            // 
            AutoScaleDimensions = new SizeF(13F, 31F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(245, 246, 250);
            Controls.Add(dgvUsers);
            Controls.Add(searchPanel);
            Controls.Add(headerPanel);
            Font = new Font("Segoe UI", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            Margin = new Padding(3, 4, 3, 4);
            MinimumSize = new Size(600, 500);
            Name = "UserManagementControl";
            Padding = new Padding(20);
            Size = new Size(800, 600);
            headerPanel.ResumeLayout(false);
            searchPanel.ResumeLayout(false);
            searchPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvUsers).EndInit();
            ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel headerPanel;
        private System.Windows.Forms.Button btnAddUser;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Panel searchPanel;
        private System.Windows.Forms.TextBox txtSearchUsers;
        private System.Windows.Forms.DataGridView dgvUsers;
        private System.Windows.Forms.DataGridViewTextBoxColumn colUserId;
        private System.Windows.Forms.DataGridViewTextBoxColumn colUsername;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRole;
        private System.Windows.Forms.DataGridViewTextBoxColumn colCreated;
        private System.Windows.Forms.DataGridViewButtonColumn colAction;
    }
}